// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Video struct {
	ID            pgtype.UUID      `json:"id"`
	Status        pgtype.UUID      `json:"status"`
	Progress      pgtype.Int4      `json:"progress"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	FileExtension string           `json:"file_extension"`
}

type VideoStatus struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}
