// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (pgtype.UUID, error)
	FindVideoById(ctx context.Context, id pgtype.UUID) (Video, error)
	ListVideos(ctx context.Context) ([]Video, error)
	ListVideosByStatus(ctx context.Context, status pgtype.UUID) ([]Video, error)
	UpdateVideoProgress(ctx context.Context, arg UpdateVideoProgressParams) error
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error
	VideoHasValidStatusToStartProcessingJob(ctx context.Context, id pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
