// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :exec
INSERT INTO videos (status, file_path) VALUES ($1, $2)
`

type CreateVideoParams struct {
	Status   pgtype.UUID `json:"status"`
	FilePath pgtype.Text `json:"file_path"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) error {
	_, err := q.db.Exec(ctx, createVideo, arg.Status, arg.FilePath)
	return err
}

const findStatusIdByName = `-- name: FindStatusIdByName :one
SELECT id FROM video_statuses WHERE status = $1 LIMIT 1
`

func (q *Queries) FindStatusIdByName(ctx context.Context, status string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findStatusIdByName, status)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findVideoById = `-- name: FindVideoById :one
SELECT id, status, progress, file_path, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) FindVideoById(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, findVideoById, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Progress,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, status, progress, file_path, created_at, updated_at FROM videos
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Progress,
			&i.FilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
