// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (status, file_extension) VALUES ($1, $2) RETURNING id
`

type CreateVideoParams struct {
	Status        pgtype.UUID `json:"status"`
	FileExtension string      `json:"file_extension"`
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createVideo, arg.Status, arg.FileExtension)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findVideoById = `-- name: FindVideoById :one
SELECT id, status, progress, created_at, updated_at, file_extension FROM videos WHERE id = $1
`

func (q *Queries) FindVideoById(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, findVideoById, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Progress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FileExtension,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, status, progress, created_at, updated_at, file_extension FROM videos
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FileExtension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByStatus = `-- name: ListVideosByStatus :many
SELECT id, status, progress, created_at, updated_at, file_extension FROM videos WHERE status = $1
`

func (q *Queries) ListVideosByStatus(ctx context.Context, status pgtype.UUID) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Progress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FileExtension,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoProgress = `-- name: UpdateVideoProgress :exec
UPDATE videos SET progress = $2 WHERE id = $1
`

type UpdateVideoProgressParams struct {
	ID       pgtype.UUID `json:"id"`
	Progress pgtype.Int4 `json:"progress"`
}

func (q *Queries) UpdateVideoProgress(ctx context.Context, arg UpdateVideoProgressParams) error {
	_, err := q.db.Exec(ctx, updateVideoProgress, arg.ID, arg.Progress)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
UPDATE videos SET status = $2 WHERE id = $1
`

type UpdateVideoStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.UUID `json:"status"`
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.db.Exec(ctx, updateVideoStatus, arg.ID, arg.Status)
	return err
}

const videoHasValidStatusToStartProcessingJob = `-- name: VideoHasValidStatusToStartProcessingJob :one
SELECT COUNT(*) > 0
FROM videos video
JOIN video_statuses vstatus ON vstatus.id = video.status
WHERE video.id = $1 AND vstatus.status = 'pending'
`

func (q *Queries) VideoHasValidStatusToStartProcessingJob(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, videoHasValidStatusToStartProcessingJob, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
