// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findVideoById = `-- name: FindVideoById :one
SELECT id, status, progress, file_path, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) FindVideoById(ctx context.Context, id pgtype.UUID) (Video, error) {
	row := q.db.QueryRow(ctx, findVideoById, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Progress,
		&i.FilePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVideos = `-- name: ListVideos :many
SELECT id, status, progress, file_path, created_at, updated_at FROM videos
`

func (q *Queries) ListVideos(ctx context.Context) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Progress,
			&i.FilePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
