// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVideo(ctx context.Context, arg CreateVideoParams) (pgtype.UUID, error)
	FindStatusIdByName(ctx context.Context, status string) (pgtype.UUID, error)
	FindVideoById(ctx context.Context, id pgtype.UUID) (Video, error)
	ListVideos(ctx context.Context) ([]Video, error)
	UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error
}

var _ Querier = (*Queries)(nil)
