// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindVideoById(ctx context.Context, id pgtype.UUID) (Video, error)
	ListVideos(ctx context.Context) ([]Video, error)
}

var _ Querier = (*Queries)(nil)
