// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
  "/videos": {
    params: {};
  };
  "/videos/manage/:id": {
    params: {
      "id": string;
    };
  };
  "/videos/:id": {
    params: {
      "id": string;
    };
  };
  "/create-video": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json" | "/videos" | "/videos/manage/:id" | "/videos/:id" | "/create-video";
  };
  "routes/devtools-probe.ts": {
    id: "routes/devtools-probe";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/videos.tsx": {
    id: "routes/videos";
    page: "/videos";
  };
  "routes/videos.manage.$id.tsx": {
    id: "routes/videos.manage.$id";
    page: "/videos/manage/:id";
  };
  "routes/videos.$id.tsx": {
    id: "routes/videos.$id";
    page: "/videos/:id";
  };
  "routes/create-video.tsx": {
    id: "routes/create-video";
    page: "/create-video";
  };
  "routes/_auth/layout.tsx": {
    id: "routes/_auth/layout";
    page: never;
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/devtools-probe": typeof import("./app/routes/devtools-probe.ts");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/videos": typeof import("./app/routes/videos.tsx");
  "routes/videos.manage.$id": typeof import("./app/routes/videos.manage.$id.tsx");
  "routes/videos.$id": typeof import("./app/routes/videos.$id.tsx");
  "routes/create-video": typeof import("./app/routes/create-video.tsx");
  "routes/_auth/layout": typeof import("./app/routes/_auth/layout.tsx");
};